### ISSUE TITLE
ai_platform_optimizer_conditional_parameters.ipynb Notebook error

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/ai-platform-samples#138]
```
+ execute notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
+ QUIET_FULL='pip install --quiet'
+ QUIET_SHORT='pip install -q'
+ grep -q 'pip install --quiet' notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
+ grep -q 'pip install -q' notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
+ sed -i 's/pip *install/pip install -q/g' notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb
+ mkdir /tmpfs/src/temp
+ cp --parents notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb /tmpfs/src/temp
+ python /tmpfs/src/gfile/executor.py --input_notebook=/tmpfs/src/temp/notebooks/samples/optimizer/ai_platform_optimizer_conditional_parameters.ipynb --timeout=15000
I0409 16:03:48.866024 140071264257792 execute.py:404] Executing notebook with kernel: python3
E0409 16:03:58.055611 140071264257792 execute.py:509] Kernel died while waiting for execute reply.
Traceback (most recent call last):
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 478, in _poll_for_reply
    msg = self.kc.shell_channel.get_msg(timeout=timeout)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmpfs/src/gfile/executor.py", line 115, in <module>
    app.run(main)
  File "/home/kbuilder/.local/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/kbuilder/.local/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmpfs/src/gfile/executor.py", line 110, in main
    timeout=FLAGS.timeout)
  File "/tmpfs/src/gfile/executor.py", line 92, in execute
    'path': str(pathlib.Path(input_notebook).parent)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 408, in preprocess
    self.set_widgets_metadata()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 348, in setup_preprocessor
    yield nb, self.km, self.kc
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/tmpfs/src/gfile/executor.py", line 52, in preprocess_cell
    return super().preprocess_cell(cell, resources, cell_index, **kwargs)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 578, in run_cell
    exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 483, in _poll_for_reply
    self._check_alive()
  File "/tmpfs/src/tf_docs_env/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 510, in _check_alive
    raise DeadKernelError("Kernel died")
nbconvert.preprocessors.execute.DeadKernelError: Kernel died
```

**Comment by gogasca** [comment]
Updated Notebook to ignore kernel restart cells
