### ISSUE TITLE
TensorFlow training fails at incompatible TF and numpy versions

### ISSUE THREAD

**Issue by lezh** [GoogleCloudPlatform/ai-platform-samples#398]
**Describe the bug**
The [tensorflow example](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/training/tensorflow/structured/base/) fails on Cloud AI Platform in both TF2.3 and TF1.5 runtime environments.

**What sample is this bug related to?**
https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/training/tensorflow/structured/base/

**Source code / logs**
When runtime version is 2.3, the training job fails with this error:
```
The replica master 0 exited with a non-zero status of 1. 
Traceback (most recent call last):
  [...]
  File "/root/.local/lib/python3.7/site-packages/tensorflow_model_analysis/api/tfma_unit.py", line 66, in <module>
    import apache_beam as beam
  File "/root/.local/lib/python3.7/site-packages/apache_beam/__init__.py", line 93, in <module>
    from apache_beam import io
  File "/root/.local/lib/python3.7/site-packages/apache_beam/io/__init__.py", line 37, in <module>
    from apache_beam.io.gcp.pubsub import *
  File "/root/.local/lib/python3.7/site-packages/apache_beam/io/gcp/pubsub.py", line 46, in <module>
    from google.cloud import pubsub
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub_v1/__init__.py", line 18, in <module>
    from google.cloud.pubsub_v1 import publisher
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub_v1/publisher/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1.publisher.client import Client
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub_v1/publisher/client.py", line 29, in <module>
    from google.cloud.pubsub_v1.gapic import publisher_client
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub_v1/gapic/publisher_client.py", line 28, in <module>
    import google.api_core.gapic_v1.client_info
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/gapic_v1/__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/gapic_v1/method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "/usr/local/lib/python3.7/dist-packages/google/api_core/grpc_helpers_async.py", line 137, in <module>
    class _WrappedUnaryUnaryCall(_WrappedUnaryResponseMixin, aio.UnaryUnaryCall):
AttributeError: module 'grpc.experimental.aio' has no attribute 'UnaryUnaryCall'
```

When runtime version is 1.5, the training job fails at this error:
```
Please upgrade numpy to >= 1.17.3 to use this pandas version
```

**To Reproduce**
To run the training job with runtime version 2.1:
```
source ./setup/variables.sh
source ./training/tensorflow/structured/base/scripts/train-cloud.sh
```

To run the training job with runtime version 1.15
```
source ./setup/variables.sh
export RUNTIME_VERSION 1.15
source ./training/tensorflow/structured/base/scripts/train-cloud.sh
```

**Expected behavior**
The jobs should succeed.

**System Information**
- Runtime version: 2.1 or 1.15
- Python version: 3.7

**Comment by kweinmeister** [comment]
The sample was originally written for TensorFlow 1.x, so I don't think the same training code will work across both 1.x and 2.x.

So, as far as the issue with 1.15 is concerned, I might suggest trying an update to `setup.py` with the higher numpy version, e.g. adding a line with `numpy==1.17.3`.

**Comment by kweinmeister** [comment]
I confirmed that I was able to resolve the dependency issues in `python setup.py install` by updating `setup.py` as needed. I will go ahead and close this issue. If you have any more information, please free to reopen it. Thanks.
