### ISSUE TITLE
Error importing scanpy package ... missing f-strings support?

### ISSUE THREAD

**Issue by Gibbsdavidl** [GoogleCloudPlatform/ai-platform-samples#68]
**Describe the bug**
Hello. I depend on a python package scanpy (https://scanpy.readthedocs.io/en/stable/)  and I can install it no problem in colaboratory, but the AI platform jupyter lab needs a python update.

**What sample is this bug related to?**
installing scanpy  (pip3 install --user scanpy)

**Source code / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-135279188441>", line 1, in <module>
    import scanpy

  File "/home/jupyter/.local/lib/python3.5/site-packages/scanpy/__init__.py", line 3, in <module>
    from .utils import check_versions, annotate_doc_types

  File "/home/jupyter/.local/lib/python3.5/site-packages/scanpy/utils.py", line 18, in <module>
    from ._settings import settings

  File "/home/jupyter/.local/lib/python3.5/site-packages/scanpy/_settings.py", line 351
    f'{k} = {v!r}'

**To Reproduce**
1. start a jupyterlab notebook
2. !pip3 install --user scanpy
3. restart kernel
4. import scanpy
5. error

**Expected behavior**
package should be imported

**System Information**
default python selection

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```
**Additional context**

**Comment by gogasca** [comment]
Will try to reproduce issue and get back to you

**Comment by Gibbsdavidl** [comment]
Just checked, this still doesn't work.  Needs 3.6 for f-strings... I'm pretty sure.

!pip3 install --user scanpy
Successfully installed anndata-0.6.20 natsort-7.0.1 numexpr-2.7.1 patsy-0.5.1 scanpy-1.4.3 statsmodels-0.11.0 tables-3.6.1 umap-learn-0.3.10

import scanpy

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-135279188441>", line 1, in <module>
    import scanpy

  File "/home/jupyter/.local/lib/python3.5/site-packages/scanpy/__init__.py", line 3, in <module>
    from .utils import check_versions, annotate_doc_types

  File "/home/jupyter/.local/lib/python3.5/site-packages/scanpy/utils.py", line 18, in <module>
    from ._settings import settings

  File "/home/jupyter/.local/lib/python3.5/site-packages/scanpy/_settings.py", line 351
    f'{k} = {v!r}'
                 ^
SyntaxError: invalid syntax

**Comment by gogasca** [comment]
I just run:

```pip install --user scanpy``` in a code cell and installed worked fine.
During import I get the same error.
In scanpy [documentation](https://pypi.org/project/scanpy/1.4.5.1/) is stated you need:  (Requires: Python >=3.6)
Since default kernel is using Python 3.5, you need to use create a new Notebook, now we support Python 3.7 by default (Python 3.7.6).

https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498

**Comment by gogasca** [comment]
You can also generate a new notebook instance using a custom container: 
https://cloud.google.com/ai-platform/notebooks/docs/custom-container
